# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_1', models.CharField(max_length=40)),
                ('line_2', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryL1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryL2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='autopartscentral.CategoryL1')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryL3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='autopartscentral.CategoryL2')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placed_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='autopartscentral.Discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='autopartscentral.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=30)),
                ('sku', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'part_images/')),
                ('availability', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.Brand')),
                ('category_l1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL1')),
                ('category_l2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL2')),
                ('category_l3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL3')),
            ],
        ),
        migrations.CreateModel(
            name='PartFeatured',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='autopartscentral.Part')),
            ],
        ),
        migrations.CreateModel(
            name='PartVehicleCompatibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=13)),
                ('default_shipping_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='autopartscentral.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='autopartscentral.VehicleMake')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTrim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trims', to='autopartscentral.VehicleEngine')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_years', to='autopartscentral.VehicleModel')),
            ],
        ),
        migrations.AddField(
            model_name='vehicleengine',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_engines', to='autopartscentral.VehicleYear'),
        ),
        migrations.AddField(
            model_name='partvehiclecompatibility',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleEngine'),
        ),
        migrations.AddField(
            model_name='partvehiclecompatibility',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleMake'),
        ),
        migrations.AddField(
            model_name='partvehiclecompatibility',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleModel'),
        ),
        migrations.AddField(
            model_name='partvehiclecompatibility',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.Part'),
        ),
        migrations.AddField(
            model_name='partvehiclecompatibility',
            name='trim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleTrim'),
        ),
        migrations.AddField(
            model_name='partvehiclecompatibility',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleYear'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='autopartscentral.Part'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autopartscentral.UserProfile'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autopartscentral.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleyear',
            unique_together=set([('year', 'model')]),
        ),
        migrations.AlterUniqueTogether(
            name='vehicletrim',
            unique_together=set([('name', 'engine')]),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together=set([('name', 'make')]),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleengine',
            unique_together=set([('name', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='partvehiclecompatibility',
            unique_together=set([('part', 'make', 'model', 'year', 'engine', 'trim')]),
        ),
        migrations.AlterUniqueTogether(
            name='categoryl3',
            unique_together=set([('category', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='categoryl2',
            unique_together=set([('category', 'name')]),
        ),
    ]
