# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-08 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_1', models.CharField(max_length=40)),
                ('line_2', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryL1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'category_images/')),
            ],
            options={
                'verbose_name_plural': 'Category Level 1',
            },
        ),
        migrations.CreateModel(
            name='CategoryL2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='autopartscentral.CategoryL1')),
            ],
            options={
                'verbose_name_plural': 'Category Level 2',
            },
        ),
        migrations.CreateModel(
            name='CategoryL3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='autopartscentral.CategoryL2')),
            ],
            options={
                'verbose_name_plural': 'Category Level 3',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placed_timestamp', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='autopartscentral.Discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='autopartscentral.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=30)),
                ('sku', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('availability', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.Brand')),
                ('category_l3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL3')),
            ],
        ),
        migrations.CreateModel(
            name='PartFeatured',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='autopartscentral.Part')),
            ],
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'part_images/')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='autopartscentral.Part')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=13)),
                ('default_shipping_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='autopartscentral.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_start', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)])),
                ('year_end', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)])),
                ('engine', models.CharField(max_length=50)),
                ('trim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Makes',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='autopartscentral.VehicleMake')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Models',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='autopartscentral.VehicleModel'),
        ),
        migrations.AddField(
            model_name='part',
            name='compatibility',
            field=models.ManyToManyField(to='autopartscentral.Vehicle'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='autopartscentral.Part'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autopartscentral.UserProfile'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autopartscentral.Address'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together=set([('name', 'make')]),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('model', 'year_start', 'year_end', 'engine', 'trim')]),
        ),
        migrations.AlterUniqueTogether(
            name='categoryl3',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='categoryl2',
            unique_together=set([('name', 'category')]),
        ),
    ]
