# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category_l1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='category_l2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL2'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category_l3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL3'),
        ),
    ]
