# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='compatibility',
            field=models.ManyToManyField(blank=True, to='autopartscentral.Vehicle'),
        ),
    ]
