# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0002_auto_20160816_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
