# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0002_auto_20161029_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category_l1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL1'),
        ),
    ]
