# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0002_auto_20161220_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='autopartscentral.UserProfile'),
            preserve_default=False,
        ),
    ]
