# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0003_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='contact_no',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='BLANK', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='BLANK', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='BLANK', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[(b'PH', b'Philippines')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(max_length=30),
        ),
    ]
