# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-18 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0003_auto_20161217_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category_l1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL1'),
            preserve_default=False,
        ),
    ]
