# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0004_auto_20160817_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.Brand'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category_l2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL2'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category_l3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL3'),
        ),
        migrations.AlterField(
            model_name='partvehiclecompatibility',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleEngine'),
        ),
        migrations.AlterField(
            model_name='partvehiclecompatibility',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleMake'),
        ),
        migrations.AlterField(
            model_name='partvehiclecompatibility',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleModel'),
        ),
        migrations.AlterField(
            model_name='partvehiclecompatibility',
            name='trim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleTrim'),
        ),
        migrations.AlterField(
            model_name='partvehiclecompatibility',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='autopartscentral.VehicleYear'),
        ),
    ]
