# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0005_auto_20161227_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PartDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_discounts', to='autopartscentral.Part')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='notes',
            new_name='customer_instructions',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='net_price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'PL', b'PLACED'), (b'CO', b'CONFIRMED'), (b'PR', b'PROCESSED'), (b'SH', b'SHIPPED'), (b'RE', b'RECEIVED')], default=b'PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='autopartscentral.PartDiscount'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_end',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_start',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)]),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autopartscentral.OrderDiscount'),
        ),
    ]
