# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0005_auto_20160817_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryl2',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='categoryl3',
            unique_together=set([('name', 'category')]),
        ),
    ]
