# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0005_auto_20160802_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pb', to='autopartscentral.Brand'),
            preserve_default=False,
        ),
    ]
