# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0006_auto_20170107_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='autopartscentral.Address'),
        ),
    ]
