# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0007_auto_20160819_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='compatibility',
            field=models.ManyToManyField(to='autopartscentral.VehicleTrim'),
        ),
    ]
