# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0008_part_compatibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='category_l1',
        ),
        migrations.RemoveField(
            model_name='part',
            name='category_l2',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='category_l3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='autopartscentral.CategoryL3'),
            preserve_default=False,
        ),
    ]
