# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0009_auto_20160906_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'part_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='image',
        ),
        migrations.AddField(
            model_name='part',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 9, 6, 12, 58, 17, 635709, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='last_modified',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 9, 6, 12, 58, 23, 795593, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partimage',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='autopartscentral.Part'),
        ),
    ]
