# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0010_auto_20160906_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)])),
                ('engine', models.CharField(max_length=50)),
                ('trim', models.CharField(max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='autopartscentral.VehicleModel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partvehiclecompatibility',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='partvehiclecompatibility',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='partvehiclecompatibility',
            name='make',
        ),
        migrations.RemoveField(
            model_name='partvehiclecompatibility',
            name='model',
        ),
        migrations.RemoveField(
            model_name='partvehiclecompatibility',
            name='part',
        ),
        migrations.RemoveField(
            model_name='partvehiclecompatibility',
            name='trim',
        ),
        migrations.RemoveField(
            model_name='partvehiclecompatibility',
            name='year',
        ),
        migrations.AlterUniqueTogether(
            name='vehicleengine',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vehicleengine',
            name='year',
        ),
        migrations.AlterUniqueTogether(
            name='vehicletrim',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vehicletrim',
            name='engine',
        ),
        migrations.AlterUniqueTogether(
            name='vehicleyear',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vehicleyear',
            name='model',
        ),
        migrations.AlterField(
            model_name='part',
            name='compatibility',
            field=models.ManyToManyField(to='autopartscentral.Vehicle'),
        ),
        migrations.DeleteModel(
            name='PartVehicleCompatibility',
        ),
        migrations.DeleteModel(
            name='VehicleEngine',
        ),
        migrations.DeleteModel(
            name='VehicleTrim',
        ),
        migrations.DeleteModel(
            name='VehicleYear',
        ),
    ]
