# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopartscentral', '0011_auto_20160906_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemake',
            options={'verbose_name_plural': 'Vehicle Makes'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name_plural': 'Vehicle Models'},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('model', 'year', 'engine', 'trim')]),
        ),
    ]
